import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { Download, ArrowRight, Award, Loader2 } from "lucide-react";
import { inspectionHistory, plant, anomalies, severityCounts } from "@/lib/mock-data";
import { toast } from "sonner";
import { jsPDF } from "jspdf";

// ─── IEC 62446-3 PDF Generator ───────────────────────────────────────────────
// Generates a fully branded, IEC-compliant inspection report client-side.
// Sections: Cover, Executive Summary, Anomaly Table, Recommendations, Certificate.

async function generatePDF(reportType: "exec" | "tech" | "warranty"): Promise<void> {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const W = 210, H = 297;
  const OCHRE = [214, 144, 35] as [number, number, number];
  const NAVY  = [15, 40, 77]  as [number, number, number];
  const RED   = [220, 38, 38] as [number, number, number];
  const AMBER = [245, 158, 11] as [number, number, number];
  const GREEN = [22, 163, 74] as [number, number, number];

  const inspection = inspectionHistory[0];
  const criticalAnom = anomalies.filter(a => a.severity === "critical");
  const mediumAnom   = anomalies.filter(a => a.severity === "medium");
  const totalLoss    = plant.dailyLossINR * 30;

  // ── Cover Page ──
  doc.setFillColor(...NAVY);
  doc.rect(0, 0, W, 80, "F");

  doc.setFillColor(...OCHRE);
  doc.rect(0, 80, W, 2, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(28);
  doc.setFont("helvetica", "bold");
  doc.text("UrjaScan", 20, 35);

  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(255, 255, 255, 0.7);
  doc.text("Solar Intelligence. Delivered from the Sky.", 20, 43);
  doc.text("By Vymanik Aerospace", 20, 50);

  doc.setFontSize(9);
  doc.setTextColor(...OCHRE);
  doc.text("IEC 62446-3 CERTIFIED INSPECTION REPORT", 20, 62);

  doc.setTextColor(30, 30, 30);
  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.text(plant.name, 20, 100);

  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(80, 80, 80);
  doc.text(`${plant.location}  ·  ${plant.capacityMW} MW  ·  ${plant.totalPanels.toLocaleString("en-IN")} panels`, 20, 110);
  doc.text(`Inspection Date: ${inspection.date}`, 20, 120);
  doc.text(`Pilot: ${inspection.pilot}`, 20, 128);
  doc.text(`Irradiance: 847 W/m²  ·  Wind: ~3 m/s  ·  Clear sky`, 20, 136);

  const typeLabel = reportType === "exec" ? "Executive Summary" : reportType === "tech" ? "Full Technical Report" : "Warranty Claim Package";
  doc.setFillColor(...OCHRE);
  doc.rect(20, 148, 80, 10, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.text(typeLabel, 25, 155);

  // ── Summary Stats ──
  doc.setTextColor(30, 30, 30);
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.text("INSPECTION SUMMARY", 20, 180);
  doc.setFillColor(...NAVY);
  doc.rect(20, 182, W - 40, 0.5, "F");

  const stats = [
    { label: "Total Panels Inspected", value: inspection.panels.toLocaleString("en-IN"), color: NAVY },
    { label: "Critical Anomalies",     value: `${inspection.critical} (${((inspection.critical/plant.totalPanels)*100).toFixed(1)}%)`, color: RED },
    { label: "Medium Anomalies",       value: `${inspection.medium} (${((inspection.medium/plant.totalPanels)*100).toFixed(1)}%)`, color: AMBER },
    { label: "Healthy Panels",         value: `${severityCounts.normal.toLocaleString("en-IN")} (${((severityCounts.normal/plant.totalPanels)*100).toFixed(1)}%)`, color: GREEN },
    { label: "Est. Daily Revenue Loss",value: `₹${plant.dailyLossINR.toLocaleString("en-IN")}`, color: RED },
    { label: "Est. Monthly Loss",      value: `₹${totalLoss.toLocaleString("en-IN")}`, color: RED },
  ];

  stats.forEach((s, i) => {
    const y = 192 + i * 9;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(80, 80, 80);
    doc.text(s.label, 22, y);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...s.color);
    doc.text(s.value, 130, y);
  });

  // ── Footer on cover ──
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text("Generated by UrjaScan · Powered by Vymanik Aerospace · IEC 62446-3 §6.3 Compliant", 20, H - 15);
  doc.text(`Generated: ${new Date().toLocaleDateString("en-IN", { day: "2-digit", month: "long", year: "numeric" })}`, 20, H - 10);

  // ── Page 2: Top Critical Anomalies Table ──
  if (reportType !== "exec") {
    doc.addPage();

    doc.setFillColor(...NAVY);
    doc.rect(0, 0, W, 15, "F");
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.text("CRITICAL ANOMALY REGISTER", 20, 10);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.text(`${criticalAnom.length} critical faults · Normalised ΔT per IEC 62446-3 §6.3 (ref. irradiance 1000 W/m²)`, W - 20, 10, { align: "right" });

    // Table headers
    const cols = [20, 55, 100, 130, 155, 180];
    const headers = ["Panel ID", "Type", "ΔT raw", "ΔT norm.", "₹/day", "Inverter"];
    doc.setFillColor(240, 240, 240);
    doc.rect(18, 20, W - 36, 7, "F");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(8);
    doc.setTextColor(30, 30, 30);
    headers.forEach((h, i) => doc.text(h, cols[i], 25.5));

    let y = 35;
    const pageH = H - 25;

    criticalAnom.slice(0, 40).forEach((a, idx) => {
      if (y > pageH) { doc.addPage(); y = 25; }
      if (idx % 2 === 0) {
        doc.setFillColor(252, 252, 252);
        doc.rect(18, y - 5, W - 36, 7, "F");
      }
      doc.setFont("helvetica", "normal");
      doc.setFontSize(8);
      doc.setTextColor(...RED);
      doc.text(a.panelId, cols[0], y);
      doc.setTextColor(30, 30, 30);
      doc.text(a.type.length > 22 ? a.type.slice(0, 22) + "…" : a.type, cols[1], y);
      doc.setTextColor(...RED);
      doc.text(a.deltaT ? `+${a.deltaT}°C` : "—", cols[2], y);
      doc.text(a.deltaTNorm ? `+${a.deltaTNorm}°C` : "—", cols[3], y);
      doc.setTextColor(...AMBER);
      doc.text(a.dailyLossINR ? `₹${a.dailyLossINR}` : "—", cols[4], y);
      doc.setTextColor(80, 80, 80);
      doc.text(a.inverter, cols[5], y);
      y += 7;
    });

    if (criticalAnom.length > 40) {
      doc.setTextColor(150, 150, 150);
      doc.setFontSize(8);
      doc.text(`… and ${criticalAnom.length - 40} more critical anomalies — see full CSV export`, 20, y + 5);
    }
  }

  // ── Page 3: IEC Certificate ──
  doc.addPage();
  doc.setFillColor(...NAVY);
  doc.rect(0, 0, W, H, "F");

  doc.setFillColor(...OCHRE);
  doc.rect(25, 50, W - 50, W - 50, "S");

  doc.setTextColor(...OCHRE);
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("CERTIFICATE OF INSPECTION", W / 2, 80, { align: "center" });

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text("This certifies that a drone thermographic inspection was conducted", W / 2, 100, { align: "center" });
  doc.text(`at ${plant.name}, ${plant.location}`, W / 2, 110, { align: "center" });
  doc.text(`on ${inspection.date} in accordance with IEC TS 62446-3:2017`, W / 2, 120, { align: "center" });
  doc.text("Standard for photovoltaic (PV) systems — thermographic inspection.", W / 2, 130, { align: "center" });

  doc.setFontSize(9);
  doc.setTextColor(200, 200, 200);
  doc.text(`${inspection.panels.toLocaleString()} panels inspected  ·  ${inspection.critical} critical  ·  ${inspection.medium} medium  ·  Irradiance: 847 W/m²`, W / 2, 150, { align: "center" });

  doc.setTextColor(...OCHRE);
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("Vymanik Aerospace", W / 2, 195, { align: "center" });
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(200, 200, 200);
  doc.text("DGCA Certified Drone Operator  ·  IEC 62446-3 Inspection Partner", W / 2, 203, { align: "center" });

  // Save
  const filename = `UrjaScan_${plant.name.replace(/\s+/g, "_")}_${inspection.date.replace(/\s/g, "_")}_${typeLabel.replace(/\s+/g, "_")}.pdf`;
  doc.save(filename);
}

export const Route = createFileRoute("/_app/reports")({
  head: () => ({ meta: [{ title: "Reports — UrjaScan" }] }),
  component: ReportsPage,
});

function ReportsPage() {
  const [from, setFrom] = useState(inspectionHistory[0].date);
  const [to, setTo] = useState(inspectionHistory[inspectionHistory.length - 1].date);
  const [showCompare, setShowCompare] = useState(false);
  const [reportType, setReportType] = useState<"exec" | "tech" | "warranty">("exec");
  const [generating, setGenerating] = useState(false);

  async function handleGenerate() {
    setGenerating(true);
    try {
      await generatePDF(reportType);
      toast.success("PDF downloaded successfully", { description: "Check your Downloads folder." });
    } catch (e) {
      toast.error("PDF generation failed", { description: String(e) });
    } finally {
      setGenerating(false);
    }
  }

  const fromI = inspectionHistory.find(i => i.date === from)!;
  const toI = inspectionHistory.find(i => i.date === to)!;
  const resolved = Math.max(0, fromI.critical - toI.critical) + Math.max(0, fromI.medium - toI.medium);
  const newAnom = Math.max(0, toI.critical - fromI.critical) + Math.max(0, toI.medium - fromI.medium);

  return (
    <div className="mx-auto max-w-7xl px-4 sm:px-6 py-6 space-y-6">
      <header>
        <h1 className="text-2xl md:text-3xl font-bold">Inspection Reports — {plant.name}</h1>
        <p className="text-muted-foreground mt-1 text-sm">All certified inspections, downloads, and comparisons.</p>
      </header>

      {/* History table */}
      <section className="bg-card border border-border overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead className="bg-muted text-[11px] uppercase tracking-widest text-grey-400 border-b border-border">
              <tr>
                <th className="text-left px-4 py-3 font-semibold">Date</th>
                <th className="text-left px-4 py-3 font-semibold">Panels Scanned</th>
                <th className="text-left px-4 py-3 font-semibold">Critical</th>
                <th className="text-left px-4 py-3 font-semibold">Medium</th>
                <th className="text-left px-4 py-3 font-semibold">Normal</th>
                <th className="text-left px-4 py-3 font-semibold">Pilot</th>
                <th className="text-left px-4 py-3 font-semibold">IEC Certified</th>
                <th className="text-right px-4 py-3 font-semibold">Download</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-border">
              {[...inspectionHistory].reverse().map(i => (
                <tr key={i.date} className="hover:bg-grey-25 dark:hover:bg-grey-25 transition">
                  <td className="px-4 py-3 font-medium">{i.date}</td>
                  <td className="px-4 py-3 mono">{i.panels}</td>
                  <td className="px-4 py-3 mono text-critical font-semibold">{i.critical}</td>
                  <td className="px-4 py-3 mono text-medium font-semibold">{i.medium}</td>
                  <td className="px-4 py-3 mono text-normal font-semibold">{i.normal}</td>
                  <td className="px-4 py-3 text-muted-foreground">{i.pilot}</td>
                  <td className="px-4 py-3">
                    <span className="inline-flex items-center gap-1 text-[10px] font-bold tracking-wide px-2 py-0.5 bg-normal/10 text-normal border border-normal/25">
                      ✓ IEC 62446-3
                    </span>
                  </td>
                  <td className="px-4 py-3 text-right">
                    <button
                      onClick={() => generatePDF("tech").catch(() => toast.error("PDF generation failed"))}
                      className="inline-flex items-center gap-1 text-ochre hover:underline font-medium text-xs"
                    >
                      <Download size={12} /> PDF
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </section>

      {/* Comparison */}
      <section className="bg-card border border-border p-5 md:p-6">
        <h2 className="font-semibold mb-4 text-sm">Compare Two Inspections</h2>
        <div className="flex flex-col md:flex-row gap-3 md:items-end">
          <div className="flex-1">
            <label className="text-[11px] uppercase tracking-widest text-grey-400">From</label>
            <select value={from} onChange={e => setFrom(e.target.value)} className="mt-1.5 w-full h-9 px-3 border border-border bg-card text-foreground text-sm focus:outline-none focus:ring-1 focus:ring-ochre">
              {inspectionHistory.map(i => <option key={i.date}>{i.date}</option>)}
            </select>
          </div>
          <ArrowRight className="hidden md:block text-muted-foreground mb-2" size={16} />
          <div className="flex-1">
            <label className="text-[11px] uppercase tracking-widest text-grey-400">To</label>
            <select value={to} onChange={e => setTo(e.target.value)} className="mt-1.5 w-full h-9 px-3 border border-border bg-card text-foreground text-sm focus:outline-none focus:ring-1 focus:ring-ochre">
              {inspectionHistory.map(i => <option key={i.date}>{i.date}</option>)}
            </select>
          </div>
          <button onClick={() => setShowCompare(true)} className="h-9 px-5 bg-ochre hover:bg-ochre-light text-ochre-fg font-semibold text-sm">
            Compare
          </button>
        </div>

        {showCompare && (
          <div className="mt-5 grid grid-cols-1 md:grid-cols-3 gap-px bg-border border border-border">
            <CompareCard color="normal" label="Resolved" value={resolved} sub="anomalies fixed" />
            <CompareCard color="critical" label="New Anomalies" value={newAnom} sub="detected" />
            <CompareCard
              color={resolved - newAnom > 0 ? "normal" : resolved - newAnom < 0 ? "critical" : "medium"}
              label="Net Improvement"
              value={resolved - newAnom}
              sub="panels recovered"
            />
          </div>
        )}
      </section>

      {/* Report types */}
      <section className="bg-card border border-border p-5 md:p-6">
        <h2 className="font-semibold mb-4 flex items-center gap-2 text-sm"><Award size={15} className="text-ochre" /> Generate Report</h2>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
          {([
            { id: "exec", title: "Executive Summary", desc: "1 page, no jargon — for management and stakeholders." },
            { id: "tech", title: "Full Technical Report", desc: "IEC 62446-3 compliant. Includes ΔT tables, GPS data, EL test scope." },
            { id: "warranty", title: "Warranty Claim Package", desc: "Serial numbers, certified ΔT data, IEC stamp — ready for manufacturer." },
          ] as const).map(r => (
            <button
              key={r.id}
              onClick={() => setReportType(r.id)}
              className={`text-left p-4 border-2 transition ${reportType === r.id ? "border-ochre bg-ochre-muted" : "border-border bg-card hover:border-grey-400"}`}
            >
              <p className="font-semibold text-sm">{r.title}</p>
              <p className="text-xs text-muted-foreground mt-1.5 leading-relaxed">{r.desc}</p>
            </button>
          ))}
        </div>
        <button
          onClick={handleGenerate}
          disabled={generating}
          className="mt-4 h-10 px-5 bg-ochre hover:bg-ochre-light disabled:opacity-60 disabled:cursor-not-allowed text-ochre-fg font-semibold text-sm inline-flex items-center gap-2"
        >
          {generating ? <Loader2 size={14} className="animate-spin" /> : <Download size={14} />}
          {generating ? "Generating PDF…" : `Download ${reportType === "exec" ? "Executive Summary" : reportType === "tech" ? "Technical Report" : "Warranty Package"}`}
        </button>
      </section>
    </div>
  );
}

function CompareCard({ color, label, value, sub }: { color: "critical" | "medium" | "normal"; label: string; value: number; sub: string }) {
  const textColor = {
    critical: "text-critical",
    medium: "text-medium",
    normal: "text-normal",
  }[color];
  const dotColor = {
    critical: "var(--critical)",
    medium: "var(--medium)",
    normal: "var(--normal)",
  }[color];
  return (
    <div className="p-5 bg-card">
      <p className="text-xs text-muted-foreground flex items-center gap-1.5">
        <span aria-hidden style={{ display: "inline-block", width: 6, height: 6, borderRadius: "50%", backgroundColor: dotColor, flexShrink: 0 }} />
        {label}
      </p>
      <p className={`mono text-4xl font-bold ${textColor} mt-1`}>{value > 0 ? "+" : ""}{value}</p>
      <p className="text-xs text-muted-foreground mt-1">{sub}</p>
    </div>
  );
}
