/**
 * Radiometric defect frames captured by the drone, one per anomaly.
 *
 * The survey KML carries the source frame in its `Label` field — e.g.
 * "23389.JPG" — which scripts/import_defect_kml.py folds into the anomaly's
 * `rgbNote` as "Image: 23389.JPG".
 *
 * The 484 frames live in public/defimages, lowercased and re-encoded from the
 * 696 MB of DJI M3T originals down to 36 MB (EXIF stripped, which also drops the
 * per-frame GPS the originals embed). There are fewer frames than anomalies —
 * 484 against 1,249 — because one frame typically captures several defects on the
 * same table, so several anomalies legitimately share an image.
 *
 * `pos` is a Block 20 leftover. That deliverable disambiguated the two modules a
 * single frame could cover with a "(pos a)" / "(pos b)" suffix; the March 2026 KML
 * has no equivalent field, so the suffix is absent and `pos` parses as null.
 * The parse is kept rather than deleted because the field costs nothing and the
 * next deliverable may carry it again — but nothing may depend on it being set.
 *
 * A THIRD SOURCE, ADDED FOR THE CSV IMPORT WIZARD
 * --------------------------------------------------
 * CsvImportWizard.tsx writes an http(s) URL into this same `rgbNote` field —
 * "Image: https://…/frame.jpg" — for a "Thermal Image URL" column an operator
 * maps during import, rather than a bare local filename. That is a second,
 * disjoint case in the regex below, not a rewrite of the first: the two forms
 * can never collide (a bare filename never starts with "http"), so the 1,249
 * survey rows keep matching exactly as they did before this existed.
 *
 * A FOURTH FIELD, ADDED FOR TASK 6 (MOBILE PROGRESSIVE LOADING)
 * --------------------------------------------------------------
 * `thumbSrc` — a ~160px WebP generated by scripts/generate_defect_thumbnails.py,
 * a few KB against the full frame's ~75KB. Only exists for the local-filename
 * form: every one of the 484 real survey frames has one (checked in at
 * public/defimages/thumb/), but a wizard-imported URL is someone else's asset
 * with no local thumbnail to generate, so `thumbSrc` is null there and the
 * consumer falls back to loading `src` directly.
 */

const DEFECT_IMAGE_DIR = "/defimages";
const DEFECT_THUMB_DIR = "/defimages/thumb";

export interface DefectImageRef {
  /** Lowercased filename as stored on disk, or null when the note carries no
   *  frame at all, OR the frame is a full URL (see `src` in that case). */
  filename: string | null;
  /** Which of the two modules in the frame the defect is on. Only ever set
   *  for the local-filename form — see the module docblock. */
  pos: "a" | "b" | null;
  /** Ready-to-use src, or null when there is no frame to show. */
  src: string | null;
  /** ~160px WebP for a fast first paint, or null — see the module docblock's
   *  "FOURTH FIELD" section for when it isn't available. */
  thumbSrc: string | null;
}

/** Parse `Image: 7531.JPG (pos a)` or `Image: https://…/frame.jpg` out of an
 *  anomaly's rgbNote. */
export function parseDefectImage(note: string | undefined | null): DefectImageRef {
  // Case-sensitive and untouched beyond the exact matched URL: lowercasing an
  // arbitrary external URL the way the local-filename branch does below could
  // break a real one (S3 keys and CDN paths are frequently case-sensitive).
  const url =
    note?.match(/Image:\s*(https?:\/\/\S+\.(?:jpe?g|png|webp|gif))(?:\s|$)/i)?.[1] ?? null;
  if (url) return { filename: null, pos: null, src: url, thumbSrc: null };

  const raw = note?.match(/Image:\s*([\w.-]+\.JPG)/i)?.[1] ?? null;
  const pos = (note?.match(/\(pos ([ab])\)/)?.[1] ?? null) as "a" | "b" | null;
  const filename = raw ? raw.toLowerCase() : null;
  const stem = filename ? filename.replace(/\.jpg$/, "") : null;
  return {
    filename,
    pos,
    src: filename ? `${DEFECT_IMAGE_DIR}/${filename}` : null,
    thumbSrc: stem ? `${DEFECT_THUMB_DIR}/${stem}.webp` : null,
  };
}
