#!/usr/bin/env python3
"""
Turn an inspection deliverable (defect KML + defect frames) into the
`_rawAnomalies` literal in src/lib/mock-data.ts.

WHY A SCRIPT AND NOT A HAND EDIT
--------------------------------
The March 2026 survey carries 1,249 defects. The May 2025 Block 20 set it
replaces carried 347 and was pasted in by hand, which is survivable once and
not twice: every re-flight would otherwise be a 1,200-line manual merge with no
way to diff intent against transcription error.

WHY THE KML AND NOT THE CSV
---------------------------
The vendor ships both `DFECT PANELS.csv` and `defpanels1.kml` with identical
schemas and the same 1,249 rows. Only the KML carries the surveyed panel
outline, and the map needs that outline: above z19.5 it draws the real footprint
rather than a dot (see PANEL_FILL_MIN_ZOOM in routes/_app/map.tsx). The CSV's
xcoord/ycoord is exactly the polygon centroid — verified to 7 decimals on the
whole set — so the KML is a strict superset and reading both would just be two
sources to keep in sync.

DEFECT CODES
------------
The KML's `id` field is a two-letter code, and no legend ships with it. The
mapping below was confirmed with the client on 2026-09-03. Six codes are
industry-standard; SP and MB were the ambiguous pair and resolved to
open-circuit and multi-bypass respectively (not "single panel" / "module
broken"). Severity banding follows the same rule the Block 20 set used: an
electrically-dead or whole-module fault is COA3, a cell-level thermal anomaly is
COA2, and an environmental finding that washes off is COA1.

USAGE
    python3 scripts/import_defect_kml.py \
        ~/Downloads/defpanels1.kml > /tmp/anomalies.ts
"""
import re
import sys
import xml.etree.ElementTree as ET

K = "{http://www.opengis.net/kml/2.2}"

# code -> (display type, severity). See DEFECT CODES above.
CODE_MAP = {
    "MM": ("Multi-Module Hotspot", "critical"),
    "BD": ("Diode Failure",        "critical"),
    "SP": ("Module Open Circuit",  "critical"),
    "MB": ("Bypassed Substring",   "critical"),
    "MC": ("Multi-Cell Hotspot",   "medium"),
    "SC": ("Cell Hotspot",         "medium"),
    "SO": ("Soiling",              "normal"),
    "SH": ("Shading",              "normal"),
}

# Survey date, from the DJI M3T EXIF DateTime on all 484 frames.
INSPECTION_DATE = "31 March 2026"

# Severity order the map and the anomaly list both expect: the file is consumed
# in order and ids are positional, so critical must come first.
SEV_RANK = {"critical": 0, "medium": 1, "normal": 2, "nodata": 3}


def num(x: float) -> str:
    """Trim float noise without losing sub-centimetre precision.

    Coordinates arrive with 13 decimals — about 10 nm, which is nine orders of
    magnitude past what a drone survey resolves. 7 decimals is ~1 cm and keeps
    the generated file a third smaller.
    """
    return f"{x:.7f}".rstrip("0").rstrip(".")


def parse(path):
    tree = ET.parse(path)
    out = []
    for pm in tree.iter(K + "Placemark"):
        data = {
            sd.get("name"): (sd.text or "").strip()
            for sd in pm.iter(K + "SimpleData")
        }
        ring = pm.find(f".//{K}LinearRing/{K}coordinates")
        if ring is None or not data:
            continue
        pts = []
        for tok in ring.text.split():
            lng, lat = tok.split(",")[:2]
            pts.append((float(lng), float(lat)))
        if len(pts) < 4:
            continue
        # Closed ring: the last vertex repeats the first, so drop it before
        # averaging or the shared corner is weighted twice and the centroid
        # drifts toward it.
        uniq = pts[:-1] if pts[0] == pts[-1] else pts
        clng = sum(p[0] for p in uniq) / len(uniq)
        clat = sum(p[1] for p in uniq) / len(uniq)

        code = data.get("id", "").upper()
        dtype, sev = CODE_MAP.get(code, ("Other", "medium"))
        out.append({
            "code": code, "type": dtype, "severity": sev,
            "rack": data.get("Rack", ""), "panel": data.get("Panel", ""),
            "module": data.get("Module", ""), "block": data.get("block", ""),
            "inv": data.get("inv", ""), "smb": data.get("smb", ""),
            "table": data.get("table", ""), "str": data.get("str", ""),
            "label": data.get("Label", ""),
            "lat": clat, "lng": clng, "ring": pts,
        })
    return out


def main(path):
    rows = parse(path)
    rows.sort(key=lambda r: (SEV_RANK[r["severity"]], r["type"],
                             int(r["rack"] or 0), int(r["panel"] or 0)))

    unknown = sorted({r["code"] for r in rows if r["code"] not in CODE_MAP})
    if unknown:
        print(f"// WARNING unmapped defect codes: {unknown}", file=sys.stderr)

    print(f"// {len(rows)} defects — generated by scripts/import_defect_kml.py")
    for i, r in enumerate(rows, 1):
        ring = ",".join(f"[{num(x)},{num(y)}]" for x, y in r["ring"])
        # `block` arrives zero-padded and inconsistently ("06", "6", "122");
        # int() normalises so two spellings of one block don't read as two.
        block = int(r["block"]) if r["block"].isdigit() else r["block"]
        print(
            f'  {{ id: "{i}", panelId: "R{r["rack"]}-P{r["panel"]}", '
            f'row: {r["rack"] or 0}, col: {r["panel"] or 0}, '
            f'type: "{r["type"]}", deltaT: null, severity: "{r["severity"]}", '
            f'string: "Table-{r["table"]}", inverter: "INV-{r["inv"]}", '
            f'status: "New", date: "{INSPECTION_DATE}", inspectionTime: "—", '
            f'rgbNote: "Image: {r["label"]}", '
            f'gps: {{ lat: {num(r["lat"])}, lng: {num(r["lng"])} }}, '
            f'block: "{block}", smb: "{r["smb"]}", stringSide: "{r["str"]}", '
            f'module: "{r["module"]}", defectCode: "{r["code"]}", '
            f'footprint: [{ring}] }},'
        )


if __name__ == "__main__":
    main(sys.argv[1])
