/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTeamRouteImport } from './routes/_app/team'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppServicesRouteImport } from './routes/_app/services'
import { Route as AppReportsRouteImport } from './routes/_app/reports'
import { Route as AppMapRouteImport } from './routes/_app/map'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppAnomaliesIndexRouteImport } from './routes/_app/anomalies/index'
import { Route as AppAnomaliesIdRouteImport } from './routes/_app/anomalies/$id'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppServicesRoute = AppServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppMapRoute = AppMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAnomaliesIndexRoute = AppAnomaliesIndexRouteImport.update({
  id: '/anomalies/',
  path: '/anomalies/',
  getParentRoute: () => AppRoute,
} as any)
const AppAnomaliesIdRoute = AppAnomaliesIdRouteImport.update({
  id: '/anomalies/$id',
  path: '/anomalies/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/map': typeof AppMapRoute
  '/reports': typeof AppReportsRoute
  '/services': typeof AppServicesRoute
  '/settings': typeof AppSettingsRoute
  '/team': typeof AppTeamRoute
  '/anomalies/$id': typeof AppAnomaliesIdRoute
  '/anomalies/': typeof AppAnomaliesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/map': typeof AppMapRoute
  '/reports': typeof AppReportsRoute
  '/services': typeof AppServicesRoute
  '/settings': typeof AppSettingsRoute
  '/team': typeof AppTeamRoute
  '/anomalies/$id': typeof AppAnomaliesIdRoute
  '/anomalies': typeof AppAnomaliesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/map': typeof AppMapRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/services': typeof AppServicesRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/team': typeof AppTeamRoute
  '/_app/anomalies/$id': typeof AppAnomaliesIdRoute
  '/_app/anomalies/': typeof AppAnomaliesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/map'
    | '/reports'
    | '/services'
    | '/settings'
    | '/team'
    | '/anomalies/$id'
    | '/anomalies/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/map'
    | '/reports'
    | '/services'
    | '/settings'
    | '/team'
    | '/anomalies/$id'
    | '/anomalies'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/dashboard'
    | '/_app/map'
    | '/_app/reports'
    | '/_app/services'
    | '/_app/settings'
    | '/_app/team'
    | '/_app/anomalies/$id'
    | '/_app/anomalies/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/team': {
      id: '/_app/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/services': {
      id: '/_app/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof AppServicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/map': {
      id: '/_app/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof AppMapRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/anomalies/': {
      id: '/_app/anomalies/'
      path: '/anomalies'
      fullPath: '/anomalies/'
      preLoaderRoute: typeof AppAnomaliesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/anomalies/$id': {
      id: '/_app/anomalies/$id'
      path: '/anomalies/$id'
      fullPath: '/anomalies/$id'
      preLoaderRoute: typeof AppAnomaliesIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppMapRoute: typeof AppMapRoute
  AppReportsRoute: typeof AppReportsRoute
  AppServicesRoute: typeof AppServicesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTeamRoute: typeof AppTeamRoute
  AppAnomaliesIdRoute: typeof AppAnomaliesIdRoute
  AppAnomaliesIndexRoute: typeof AppAnomaliesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppMapRoute: AppMapRoute,
  AppReportsRoute: AppReportsRoute,
  AppServicesRoute: AppServicesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTeamRoute: AppTeamRoute,
  AppAnomaliesIdRoute: AppAnomaliesIdRoute,
  AppAnomaliesIndexRoute: AppAnomaliesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
